package hu.bme.wikidatagame.WikiDataGame

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.ResponseBody


@Controller
@RequestMapping(path = arrayOf("/demo"))
class MoviesController {

    @Autowired // This means to get the bean called userRepository
    private// Which is auto-generated by Spring, we will use it to handle the data
    lateinit var moviesRepository: MoviesRepository

    @GetMapping(path = arrayOf("/all"))
    @ResponseBody
    fun getallUsers(): Iterable<Movies> {
        return moviesRepository.findAll()
    }
}